### PR TITLE
#10: use Popover from buildo-react-components (closes #10)

### LINKED ISSUE #10: use Popover from buildo-react-components
NOTE: the API of the new `Popover` from `buildo-react-components` is structured differently

- update `Tooltip`
- update `DropdownMenu`
- update `PopoverIcon`

### PR DESCRIPTION
**Pull request by francescogior**
Issue #10

### CODE REVIEW

**Comment by francescogior** [comment]
@FrancescoCioria I forced `Tooltip` to use `type='absolute'` because otherwise most of the tooltips in LOL were invisible

**Comment by FrancescoCioria** [comment]
Sorry, I hadn't noticed this PR...
Anyway, looks fine! :+1: :dart:

**Comment by FrancescoCioria** [comment]
actually no, you didn't update Tooltip to the new props structure. I'll fix it

**Comment by giogonzo** [comment]
looks good, let me try this

**Comment by giogonzo** [comment]
after a rebase on master, looks API-breaking in some way:
```
"Invalid prop "popover" supplied to Tooltip, should be a {content: String, position: ?String, anchor: ?String, onShow: ?Function, onHide: ?Function, dismissOnScroll: ?Boolean, className: ?String, id: ?String, maxWidth: ?Number | String}. Detected errors (1): 1. Invalid value undefined supplied to {content: String, position: ?String, anchor: ?String, onShow: ?Function, onHide: ?Function, dismissOnScroll: ?Boolean, className: ?String, id: ?String, maxWidth: ?Number | String} "
```

**Comment by FrancescoCioria** [comment]
Yes, as I said the API of `Popover` (and as consequence of `Tooltip` and `TooltippedIcon`) has slightly changed. I'll fix it in LOL

**Pull request merged**
