### PR TITLE
#19: softLoading option for Panel (closes #19)

### LINKED ISSUE #19: softLoading option for Panel

### PR DESCRIPTION
**Pull request by giogonzo**
Issue #19

### CODE REVIEW

**Comment by giogonzo** [comment]
future reviewer: do not consider this is basically custom LOL style, we'll split things up in the future

**Comment by francescogior** [comment]
:+1:

**Comment by giogonzo** [comment]
@francescogior added `softLoadingDelay` handling in last commit

**Comment by giogonzo** [comment]
@FrancescoCioria moved `isSoftLoadingState` logic close to the rest of softLoading timing logic

**Pull request merged**
